const videoentryarray = [
  {
    videocode: "OwnFf5oZil8",
    thumbnail:
      "https://i.ytimg.com/vi/OwnFf5oZil8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCbp_NKCk7zQQCQ1VIG2C-oi2Rahg",
    time: 21,
    name: "The Blockchain Revolution",
    description: "",
    stars: 4,
    type: "finance",
    prime: false,
    date: "Dec 19, 2020",
    datenos: 1608316200000,
  },
  {
    videocode: "um2Q9aUecy0",
    thumbnail:
      "https://i.ytimg.com/vi/um2Q9aUecy0/hq720.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDDud7orgTc1alXS0crNBAWhy4VPg",
    time: 51,
    name: "Our Planet | Jungles | FULL EPISODE | Netflix",
    description: "",
    stars: 4.3,
    type: "nature",
    prime: true,
    date: "Apr 17, 2020",
    datenos: 1587061800000,
  },
  {
    videocode: "r9PeYPHdpNo",
    thumbnail:
      "https://i.ytimg.com/vi/r9PeYPHdpNo/hq720.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&amp;rs=AOn4CLBQjPLdZ0CwGhT0txReEAVSnVHH5Q",
    time: 50,
    name: "Our Planet | Coastal Seas | FULL EPISODE | Netflix",
    description: "",
    stars: 4.4,
    type: "nature",
    prime: true,
    date: "Apr 17, 2020",
    datenos: 1587061800000,
  },
  {
    videocode: "pLZf5E2d9jc",
    thumbnail:
      "https://i.ytimg.com/vi/pLZf5E2d9jc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWHJBseQBHdRgA_HJV8oOQ0AFkjQ",
    time: 25,
    name: "Culinary Colonisation: Fast Food and Big Pharma in India",
    description: "",
    stars: 4.2,
    type: "food",
    prime: false,
    date: "Jul 19, 2019",
    datenos: 1563474600000,
  },
  {
    videocode: "8LAFIDR56Sw",
    thumbnail:
      "https://i.ytimg.com/vi/8LAFIDR56Sw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7CaksPZVmbfLpOYbb80ckFfDcvQ",
    time: 18,
    name: "Is Organic Food Really Worth It?",
    description: "",
    stars: 4.8,
    type: "food",
    prime: false,
    date: "Sep 21, 2021",
    datenos: 1632162600000,
  },
  {
    videocode: "1OO5YpCevfY",
    thumbnail:
      "https://i.ytimg.com/vi/1OO5YpCevfY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC9d4fMBqqvGU4nnuprvE0B5KtNkw",
    time: 11,
    name: "Lab-Grown Real Meat is Finally Here",
    description: "",
    stars: 4.5,
    type: "food",
    prime: false,
    date: "Mar 17, 2021",
    datenos: 1615919400000,
  },
  {
    videocode: "KIEOuKD9KX8",
    thumbnail:
      "https://i.ytimg.com/vi/KIEOuKD9KX8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&amp;rs=AOn4CLDWsthG3X5W_cjZu-fLXI0-bSC-Ug",
    time: 26,
    name: "When food becomes scarce � high-tech farms of the future | DW Documentary",
    description: "",
    stars: 4.7,
    type: "food",
    prime: false,
    date: "Nov 28, 2020",
    datenos: 1606501800000,
  },
  {
    videocode: "ZCFkWDdmXG8",
    thumbnail:
      "https://i.ytimg.com/vi/ZCFkWDdmXG8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDMqpIzpLZAvzGAxU3FsS3a4CLD8A",
    time: 18,
    name: "Explained | The Stock Market | FULL EPISODE | Netflix",
    description: "",
    stars: 3.9,
    type: "finance",
    prime: false,
    date: "Apr 17, 2020",
    datenos: 1587061800000,
  },
  {
    videocode: "9RbL8lTsITY",
    thumbnail:
      "https://i.ytimg.com/vi/9RbL8lTsITY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCwC_ORzQP6sxlW6cm2kjtCzmnGXw",
    time: 53,
    name: "The Power of the Fed (full documentary) | FRONTLINE",
    description: "",
    stars: 4.2,
    type: "finance",
    prime: false,
    date: "Jul 14, 2021",
    datenos: 1626201000000,
  },
  {
    videocode: "W3JZ1j5R8SI",
    thumbnail:
      "https://i.ytimg.com/vi/W3JZ1j5R8SI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDqz1K-beiQjOgguSQ9JguN1N9MMQ",
    time: 58,
    name: "How to Spend $75 billion to do the Most Good | Bjorn Lomborg | Talks at Google",
    description: "",
    stars: 5,
    type: "nature",
    prime: false,
    date: "May 20, 2014",
    datenos: 1400524200000,
  },
  {
    videocode: "R2DU85qLfJQ",
    thumbnail:
      "https://i.ytimg.com/vi/R2DU85qLfJQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAzhqbggOIr_K8yyMutgfzdVne59Q",
    time: 49,
    name: "Our Planet | Fresh Water | FULL EPISODE | Netflix",
    description: "",
    stars: 4.3,
    type: "nature",
    prime: false,
    date: "Apr 17, 2020",
    datenos: 1587061800000,
  },
  {
    videocode: "MFO6OtnmEDo",
    thumbnail:
      "https://i.ytimg.com/vi/MFO6OtnmEDo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBRB9uyuNYEonqOGX44_5j6JrLyrA",
    time: 18,
    name: "Money: Humanity's Biggest Illusion",
    description: "",
    stars: 4.1,
    type: "finance",
    prime: false,
    date: "Sep 24, 2021",
    datenos: 1632421800000,
  },
];
module.exports = { videoentryarray };
